[package]
name = "nfetch"
version = "0.1.0"
authors = ["melike2d <gino@dimensional.fun>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
sys-info = "0.9.0"
whoami = "1.1.2"
